insert into "dba"."tbsport" ("sport") values ('tennis');

insert into "dba"."tbtournoi" ("tournoi", "sportId") values ('Roland Garros','1');
insert into "dba"."tbtournoi" ("tournoi", "sportId") values ('US Open','1');
insert into "dba"."tbtournoi" ("tournoi", "sportId") values ('Wimbledon','1');
insert into "dba"."tbtournoi" ("tournoi", "sportId") values ('Open Australie','1');


insert into "dba"."tbjoueur" ("joueurNom", "joueurPrenom") values ('Nadal','Rafael');
insert into "dba"."tbjoueur" ("joueurNom", "joueurPrenom") values ('Djokovic','Novak');
insert into "dba"."tbjoueur" ("joueurNom", "joueurPrenom") values ('Wawrinka','Stanislas');
insert into "dba"."tbjoueur" ("joueurNom", "joueurPrenom") values ('Federer','Roger');
insert into "dba"."tbjoueur" ("joueurNom", "joueurPrenom") values ('Murray','Andy');
insert into "dba"."tbjoueur" ("joueurNom", "joueurPrenom") values ('Halep','Simona');
insert into "dba"."tbjoueur" ("joueurNom", "joueurPrenom") values ('Ostapenko','Jelena');
insert into "dba"."tbjoueur" ("joueurNom", "joueurPrenom") values ('Williams','Serena');
insert into "dba"."tbjoueur" ("joueurNom", "joueurPrenom") values ('Osaka','Naomi');
insert into "dba"."tbjoueur" ("joueurNom", "joueurPrenom") values ('Stephens','Sloane');
insert into "dba"."tbjoueur" ("joueurNom", "joueurPrenom") values ('Kerber','Angelique');
insert into "dba"."tbjoueur" ("joueurNom", "joueurPrenom") values ('Pennetta','Flavia');
insert into "dba"."tbjoueur" ("joueurNom", "joueurPrenom") values ('Muguruza','Garbiñe');
insert into "dba"."tbjoueur" ("joueurNom", "joueurPrenom") values ('Kenin','Sofia');
insert into "dba"."tbjoueur" ("joueurNom", "joueurPrenom") values ('Wozniacki','Caroline');
insert into "dba"."tbjoueur" ("joueurNom", "joueurPrenom") values ('annulé', ' ');

insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2016','3','1');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2017','2','1');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2018','1','1');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2019','1','1');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2020','16','1');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2016','8','1');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2017','13','1');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2018','7','1');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2019','6','1');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2016','2','2');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2017','3','2');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2018','1','2');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2019','2','2');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2020','16','2');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2016','12','2');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2017','11','2');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2018','10','2');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2019','9','2');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2016','8','3');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2017','8','3');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2018','13','3');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2019','11','3');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2020','16','3');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2016','2','3');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2017','5','3');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2018','4','3');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2019','4','3');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2020','2','3');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2016','8','4');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2017','11','4');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2018','8','4');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2019','15','4');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2020','14','4');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2016','2','4');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2017','2','4');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2018','4','4');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2019','4','4');
insert into "dba"."tbparticipation" ("annee","joueurId","tournoiId") values ('2020','2','4');
