insert into "dba"."tbtournoi" ("tournoi", "sportId") values ('Roland Garros','1');
insert into "dba"."tbtournoi" ("tournoi", "sportId") values ('US Open','1');
insert into "dba"."tbtournoi" ("tournoi", "sportId") values ('Wimbledon','1');
insert into "dba"."tbtournoi" ("tournoi", "sportId") values ('Open Australie','1');

insert into "dba"."tbsport" ("sport") values ('tennis');

insert into "dba"."tbjoueur" ("joueur") values ('Rafael Nadal');
insert into "dba"."tbjoueur" ("joueur") values ('Novak Djokovic');
insert into "dba"."tbjoueur" ("joueur") values ('Stanislas Wawrinka');
insert into "dba"."tbjoueur" ("joueur") values ('Roger Federer');
insert into "dba"."tbjoueur" ("joueur") values ('Andy Murray');
insert into "dba"."tbjoueur" ("joueur") values ('Simona Halep');
insert into "dba"."tbjoueur" ("joueur") values ('Jelena Ostapenko');
insert into "dba"."tbjoueur" ("joueur") values ('Serena Williams');
insert into "dba"."tbjoueur" ("joueur") values ('Naomi Osaka');
insert into "dba"."tbjoueur" ("joueur") values ('Sloane Stephens');
insert into "dba"."tbjoueur" ("joueur") values ('Angelique Kerber');
insert into "dba"."tbjoueur" ("joueur") values ('Flavia Pennetta');
insert into "dba"."tbjoueur" ("joueur") values ('Garbiñe Muguruza');
insert into "dba"."tbjoueur" ("joueur") values ('Sofia Kenin');
insert into "dba"."tbjoueur" ("joueur") values ('Caroline Wozniacki');
insert into "dba"."tbjoueur" ("joueur") values ('annulé');

insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('1', '3', '2016');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('1', '2', '2017');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('1', '1', '2018');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('1', '1', '2019');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('1', '16', '2020');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('1', '8', '2016');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('1', '13', '2017');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('1', '7', '2018');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('1', '6', '2019');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('1', '16', '2020');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('2', '2', '2016');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('2', '3', '2017');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('2', '1', '2018');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('2', '2', '2019');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('2', '16', '2020');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('2', '12', '2016');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('2', '11', '2017');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('2', '10', '2018');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('2', '9', '2019');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('2', '16', '2020');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('3', '8', '2016');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('3', '8', '2017');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('3', '13', '2018');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('3', '11', '2019');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('3', '16', '2020');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('3', '2', '2016');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('3', '5', '2017');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('3', '4', '2018');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('3', '4', '2019');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('3', '2', '2020');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('4', '8', '2016');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('4', '11', '2017');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('4', '8', '2018');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('4', '15', '2019');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('4', '14', '2020');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('4', '3', '2016');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('4', '3', '2017');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('4', '3', '2018');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('4', '3', '2019');
insert into "dba"."tbannee" ("tournoiId", "joueurId", "annee") values ('4', '3', '2020');

